nelmio_api_doc:
    documentation:
        info:
            title: ai-university test-case
            description: https://github.com/ko4a/AIUniversityTestCase
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
