reservations:
  type: annotation
  resource: App\Controller\ReservationController
  prefix: api

tickets:
  type: annotation
  resource: App\Controller\TicketController
  prefix: api

callbacks:
  type: annotation
  resource: App\Controller\CallbackController
  prefix: api